### ISSUE TITLE
Pageres still not showing new options

### ISSUE THREAD

**Issue by chandrantwins** [keepgoingwm/pageres-integration#1]
Dear developer,

Thanks for enhancing pageres. But i could not see new feauture after install. How to get new feauture show in command line.
Still its showing old options

   Options
   -v, --verbose            Verbose output
   -c, --crop               Crop to the set height
   -d, --delay=<seconds>    Delay screenshot capture

**Comment by awamwang** [comment]
After installation, use `pageresi` as cmd name. It's a doc bug.

As a temporary modfication for our using, this repository hasn't that good quality. Maybe Issues at Pageres(https://github.com/sindresorhus/pageres-cli) is better choice. Sorry for that.
